config/routes.rb
Rails.application.routes.draw do
  resources :abstracts
  
  root 'abstracts#new'

end

app/models/abstract.rb
class Abstract < ActiveRecord::Base
  ABSTRACT_SIZE=3500
  validates :last_name, :presence => true
  validates :title, :presence => true
  validates :organization, :presence => true
  validates :abstract, length: {within: 10..ABSTRACT_SIZE}
  validates :email, :format => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
end

app/controllers/abstracts_controller.rb
class AbstractsController < ApplicationController
  before_action :set_abstract, only: [:show, :edit, :update, :destroy]
  before_filter :trim_abstract
  
  def trim_abstract
    if params[:abstract]
      if params[:abstract][:abstract]
        params[:abstract][:abstract] = (params[:abstract][:abstract])[0..Abstract::ABSTRACT_SIZE]
      end
    end
  end
        
  # GET /abstracts
  # GET /abstracts.json
  def index
    @abstracts = Abstract.all.sort { |a, b| a.created_at <=> b.created_at }
    logger.info "found #{@abstracts.size} abstracts"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @abstracts }
    end
  end

  # GET /abstracts/1
  # GET /abstracts/1.json
  def show
  end

  # GET /abstracts/new
  def new
    @abstract = Abstract.new
  end

  # GET /abstracts/1/edit
  def edit
  end

  # POST /abstracts
  # POST /abstracts.json
  def create
    logger.info("Create: #{abstract_params.inspect}")
    @abstract = Abstract.new(abstract_params)
    logger.info("After new: #{@abstract.inspect}")

    respond_to do |format|
      if @abstract.save
        mail = AbstractMailer.submitted(@abstract)
        mail.deliver
        
        format.html { redirect_to @abstract, notice: 'Abstract was successfully created.' }
        format.json { render :show, status: :created, location: @abstract }
      else
        format.html { render :new }
        format.json { render json: @abstract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abstracts/1
  # PATCH/PUT /abstracts/1.json
  def update
    respond_to do |format|
      if @abstract.update(abstract_params)
        format.html { redirect_to @abstract, notice: 'Abstract was successfully updated.' }
        format.json { render :show, status: :ok, location: @abstract }
      else
        format.html { render :edit }
        format.json { render json: @abstract.errors, status: :unprocessable_entity }
      end
    end
  end

  # # DELETE /abstracts/1
  # # DELETE /abstracts/1.json
  # def destroy
  #   @abstract.destroy
  #   respond_to do |format|
  #     format.html { redirect_to abstracts_url, notice: 'Abstract was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abstract
      @abstract = Abstract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abstract_params
      params.require(:abstract).permit(:first_name, :last_name, :email, :organization, :country, :other_authors, :title, :abstract)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/abstracts_helper.rb
module AbstractsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abstracts/_form.html.erb
<script type='text/javascript'>
  var abstract_size = <%= Abstract::ABSTRACT_SIZE %>;
  function textCounter( field, countfield, maxlimit ) {
   if ( field.value.length > maxlimit ) {
    field.value = field.value.substring( 0, maxlimit );
    field.blur();
    field.focus();
    return false;
   } else {
    countfield.value = maxlimit - field.value.length;
   }
  }
</script>
<%= form_for(@abstract) do |f| %>
  <% if @abstract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@abstract.errors.count, "error") %> prohibited this abstract from being saved:</h2>

      <ul>
      <% @abstract.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
    <table>
      <tr><td colspan="6"><h3>Primary Author: </h3></td></tr>
      <tr>    
        <div class="field"><td><%= f.label :first_name %></td><td><%= f.text_field :first_name, size: 20 %></td></div>
        <div class="field"><td><%= f.label :last_name %></td><td><%= f.text_field :last_name, size: 20 %></td></div>
      </tr>
      <tr>
        <div class="field"><td><%= f.label :email %></td><td><%= f.text_field :email, size: 20 %></td></div>
      </tr>
      <tr>
        <div class="field"><td><%= f.label :organization, "Organization or affiliation" %></td><td><%= f.text_field :organization, size: 20 %></td></div>
        <div class="field"><td><%= f.label :country %></td><td colspan="5"><%= f.text_field :country, size: 20 %></td></div>
      </tr>
      <tr><td colspan="6"><h3>Other Authors: </h3></td></tr>
      <tr>
        <div class="field">
          <td><%= f.label :other_authors %></td>
          <td colspan="5"><%= f.text_field :other_authors, :size => 69 %></td>
        </div>
      </tr>
      <tr><td colspan="6"><h3>Paper Submitted:</h3></td></tr>
      <tr>
        <div class="field">
          <td><%= f.label :title, 'Title' %></td>
          <td colspan="5"><%= f.text_field :title, :size => 69 %></td>
        </div>
      </tr>
      <tr>
        <div class="field">
          <td><%= f.label :abstract, "Abstract (max #{Abstract::ABSTRACT_SIZE} chars)" %></td>
          <td colspan="5"><%= f.text_area :abstract, :cols => 65, :rows => 16, :onblur => "textCounter(this,this.form.counter,abstract_size);", :onkeyup => "textCounter(this,this.form.counter,abstract_size);" %>
            <!-- Got this snippet from http://www.java-samples.com/showtutorial.php?tutorialid=733 -->
            <br/>Remaining: <input onblur="textCounter(this.form.recipients,this,abstract_size);" disabled  onfocus="this.blur();" tabindex="999" maxlength="3" size="3" value="<%= Abstract::ABSTRACT_SIZE %>" name="counter"></td>
        </div>
      </tr>
      <tr>
        <div class="actions">
          <td colspan="6"><%= f.submit 'Submit' %></td>
        </div>
      </tr>
      <tr><td colspan="6">If you prefer to send your abstract as an email attachment, please email it to <%= link_to 'hartemink@wisc.edu', 'mailto:hartemink@wisc.edu'%></td></tr>
    </table>
  </div>
<% end %>

app/views/abstracts/edit.html.erb
<h1>Editing abstract</h1>

<%= render 'form' %>

<%= link_to 'Show', @abstract %> |
<%= link_to 'Back', abstracts_path %>

app/views/abstracts/index.html.erb
<h1>Online Abstract Submission Coming Soon!</h1>
<p>Watch this space for an online form to submit your abstracts to the conference.</p>

app/views/abstracts/new.html.erb
<h1>Please enter details for your abstract</h1>

<%= render 'form' %>

app/views/abstracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @abstract.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @abstract.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @abstract.email %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @abstract.organization %>
</p>

<p>
  <strong>Country:</strong>
  <%= @abstract.country %>
</p>

<p>
  <strong>Other authors:</strong>
  <%= @abstract.other_authors %>
</p>

<p>
  <strong>Title:</strong>
  <%= @abstract.title %>
</p>

<p>
  <strong>Abtract:</strong>
  <%= @abstract.abstract %>
</p>

<%= link_to 'Edit', edit_abstract_path(@abstract) %> |
<%= link_to 'Back', abstracts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soilmorpho</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>